//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunShimmer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master()
        {
            this.Records = new HashSet<Record>();
        }

        public string GetPhoto
        {
            get
            {
                return AppDomain.CurrentDomain.BaseDirectory + @"\Images\Masters\" + Photo;
            }
        }

        public string FullName
        {
            get
            {
                return SecondName + " " + FirstName + " " + Patronymic;
            }
        }

        public int MasterId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Patronymic { get; set; }
        public string Photo { get; set; }
        public string PhoneNumber { get; set; }
        public string Qualification { get; set; }
        public string WorkSchedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
    }
}
