//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunShimmer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvisionService
    {
        public int ProvisionServiceId { get; set; }
        public System.DateTime TimeOfProvision { get; set; }
        public int Price { get; set; }
        public Nullable<int> SertificateId { get; set; }
        public int ServiceId { get; set; }
        public int RecordId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Record Record { get; set; }
        public virtual PurchaseSertificate PurchaseSertificate { get; set; }
        public virtual Service Service { get; set; }
    }
}
