//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunShimmer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseSertificate()
        {
            this.ProvisionServices = new HashSet<ProvisionService>();
            this.PurchaseProducts = new HashSet<PurchaseProduct>();
        }

        public string Status
        {
            get
            {
                if (SertificateStatus == false) return "Не активирован";
                else return "Активирован";
            }
        }

        public int SertificateId { get; set; }
        public System.DateTime TimeOfActivation { get; set; }
        public bool SertificateStatus { get; set; }
        public int SertificateTypeId { get; set; }
        public int RestSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvisionService> ProvisionServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseProduct> PurchaseProducts { get; set; }
        public virtual SertificateType SertificateType { get; set; }
    }
}
