//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunShimmer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.ProvisionServices = new HashSet<ProvisionService>();
        }

        public string FullName
        {
            get
            {
                return Client.FullName + " " + TimeOfRecord.ToString();
            }
        }

        public int RecordId { get; set; }
        public Nullable<System.DateTime> DatefApplication { get; set; }
        public bool ApplicationView { get; set; }
        public string PhoneNumber { get; set; }
        public string Comment { get; set; }
        public System.DateTime TimeOfRecord { get; set; }
        public string RecordStatus { get; set; }
        public int MasterId { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Master Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvisionService> ProvisionServices { get; set; }
    }
}
